theme: jekyll-theme-tactile
title: ⋈ mr. veato
description: bassist, game developer, top rated freelancer
show_downloads: false
<script data-ad-client="ca-pub-5983069358981928" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
